### ISSUE TITLE
No module named src.functions

### ISSUE THREAD

**Issue by vinnitu** [corochann/SeRanet#1]
I use python2

```
$ python src/inference.py image.png 
prepare model
Traceback (most recent call last):
  File "src/inference.py", line 91, in <module>
    import arch.seranet_v1 as model_arch
  File "/home/user/SeRanet/src/arch/seranet_v1.py", line 8, in <module>
    import src.functions as CF
ImportError: No module named src.functions
```

**Comment by corochann** [comment]
Can you try
`PYTHONPATH='.' python src/inference.py image.png`

**Comment by vinnitu** [comment]
Thx! It works.
