### ISSUE TITLE
Issue in importing ConvolutionRBM

### ISSUE THREAD

**Issue by amith-moorkoth** [corochann/SeRanet#2]
prepare model
Traceback (most recent call last):
  File "src/inference.py", line 91, in <module>
    import arch.seranet_v1 as model_arch
  File "C:\Users\amith\Desktop\im\src\arch\seranet_v1.py", line 10, in <module>
    from convolution_rbm import ConvolutionRBM
ImportError: No module named 'convolution_rbm'

when try to execute on windows

**Comment by amith-moorkoth** [comment]
solved by adding arch.convolution_rbm
