### ISSUE TITLE
Error on using inference.py

### ISSUE THREAD

**Issue by tharuniitk** [corochann/SeRanet#4]
Hi
thanks for the implementation of Image SRCNN
After installation as mentioned in readme.txt, when I run inference.py with input and output image arguments on a GPU, I get the following error

(keras) tharun@nvidia-All-Series:~/keras/SeRanet$ python src/inference.py /home/tharun/Desktop/ID099.jpg /home/tharun/Desktop/11.jpg -g 1
prepare model
Traceback (most recent call last):
  File "src/inference.py", line 92, in <module>
    model = model_arch.seranet_v1(inout_ch=inout_ch)
  File "/home/tharun/keras/SeRanet/src/arch/seranet_v1.py", line 27, in __init__
    seranet_v1_crbm=seranet_v1_crbm(inout_ch),
  File "/home/tharun/keras/SeRanet/src/arch/seranet_v1.py", line 130, in __init__
    crbm1=ConvolutionRBM(inout_ch, 64, 5, wscale=1.),
  File "/home/tharun/keras/SeRanet/src/arch/convolution_rbm.py", line 51, in __init__
    conv=L.Convolution2D(in_channels, out_channels, ksize, stride=stride, wscale=wscale),
  File "/home/tharun/keras/local/lib/python2.7/site-packages/chainer/links/connection/convolution_2d.py", line 112, in __init__
    argument.assert_kwargs_empty(kwargs)
  File "/home/tharun/keras/local/lib/python2.7/site-packages/chainer/utils/argument.py", line 18, in assert_kwargs_empty
    parse_kwargs(kwargs)
  File "/home/tharun/keras/local/lib/python2.7/site-packages/chainer/utils/argument.py", line 12, in parse_kwargs
    raise TypeError('got unexpected keyword argument(s) %s' % args)
TypeError: got unexpected keyword argument(s) 'wscale'

Hope to get it resolved ..
Thanks in advance

Best
Tharun

**Comment by corochann** [comment]
Sorry it might be not compatible with latest chainer version 2.
Could you try using chainer version 1 with following command?

pip uninstall chainer
pip install chainer==1.24 --no-cache-dir

**Comment by tharuniitk** [comment]
Thank you, code is running, #4
